[phases.setup]
nixPkgs = ["...", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "pip3 --version",
  "pip3 install --break-system-packages -r backend/requirements-web.txt"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
